defines
    =
    {@+:define | ignore}+ $
    ;


comment
    =
    ?/\/\*\s*/? ~ @:?/(?:.|\n)*?(?=\s*\*\/)/?? ?/\s*\*\//?
    ;


trailing_comment
    =
    ?/\/\*\s*/? ~ @:?/.*?(?=\s*\*\/)/? ?/\s*\*\//?
    ;


define(Define)
    =
    {prologue+:comment /[ \t\n]*/}
    '#define'
    /[ \t]+/
    symbol:symbol
    {/[ \t]+/ value+:value}+
    [/[ \t]*/ comment:trailing_comment]
    /\n?/
    ;


symbol
    =
    /[^\s]+/
    ;


value
    =
      '((' /[^\s]+\)\s/ @:?/[^\s\/()]+/? ')'
    | '(' @:?/[^\s\/()]+/? ')'
    | @:?/[^\s\/()]+/?
    ;


ignore
    =
    /[^\n]*\n?/
    ;

